version: 2
updates:
  # Configure dependency updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Configure dependency updates for npm (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Configure dependency updates for pip (Python)
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
