# Generated by Django 5.1.1 on 2024-10-02 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0002_category_device_edge_flow_node_delete_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="connection_type",
        ),
        migrations.AddField(
            model_name="category",
            name="connection_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("wifi", "wifi"),
                        ("bluetooth", "bluetooth"),
                        ("ethernet", "ethernet"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=3,
            ),
        ),
    ]
