# Generated by Django 5.1.1 on 2024-10-11 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_remove_category_connection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='expected_response',
        ),
        migrations.AddField(
            model_name='category',
            name='communication_protocols',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('wifi', 'WiFi'),
                        ('bluetooth', 'Bluetooth'),
                        ('lte', 'LTE'),
                    ],
                    max_length=50,
                ),
                default=list,
                size=3,
            ),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(
                choices=[('Action', 'Action'), ('Assert', 'Assert')],
                default='Action',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='connection_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('adb', 'ADB'), ('uart', 'UART')], max_length=50
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
