# Generated by Django 5.1.1 on 2024-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_device_connection_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='communication_ids',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='flow',
            name='edges',
            field=models.ManyToManyField(blank=True, to='data_manager.edge'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='data_manager.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='x_pos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='y_pos',
            field=models.IntegerField(blank=True),
        ),
    ]
