# Generated by Django 5.1.1 on 2024-11-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'data_manager',
            '0006_device_communication_ids_alter_flow_edges_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='api_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='assertion_method',
            field=models.CharField(
                blank=True,
                choices=[('api', 'API'), ('uart', 'UART')],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='node',
            name='expected_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='expected_uart_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='timeout',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
