# Generated by Django 5.1.1 on 2024-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'data_manager',
            '0006_device_communication_ids_alter_flow_edges_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='communication_ids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_ids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='x_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='y_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
