# Generated by Django 5.1.1 on 2024-11-08 00:44

import os

import yaml
from django.conf import settings
from django.db import migrations


def add_default_nrf_nodes(apps, schema_editor):
    Node = apps.get_model("data_manager", "Node")

    default_nodes_path = os.path.join(settings.BASE_DIR, 'default_nodes.yaml')

    with open(default_nodes_path, "r") as file:
        data = yaml.safe_load(file)

    nrf_connect_func = data['default_node_functions']['nrf_connect']
    nrf_custom_func = data['default_node_functions']['nrf_custom']

    Node.objects.create(
        label="Default nRF connect node",
        node_type="Action",
        function=nrf_connect_func,
    )

    Node.objects.create(
        label="Default nRF custom script node",
        node_type="Action",
        function=nrf_custom_func,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0009_alter_node_device'),
    ]

    operations = [
        migrations.RunPython(add_default_nrf_nodes),
    ]
