# Generated by Django 5.1.1 on 2024-11-12 00:42

import os

import yaml
from django.conf import settings
from django.db import migrations


def add_default_api_node(apps, schema_editor):
    Node = apps.get_model("data_manager", "Node")

    default_nodes_path = os.path.join(settings.BASE_DIR, 'default_nodes.yaml')

    with open(default_nodes_path, "r") as file:
        data = yaml.safe_load(file)

    api_assort_func = data['default_node_functions']['api_assert']

    Node.objects.create(
        label="Default API assert node",
        node_type="Assert",
        function=api_assort_func,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_add_default_nrf_nodes'),
    ]

    operations = [
        migrations.RunPython(add_default_api_node),
    ]
