name: Backend CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup python and cache dependencies
        uses: actions/setup-python@v5
        with:
            python-version: "3.10"
            cache: 'pip'
      - name: Install pip dependencies
        working-directory: ./server
        run: pip install -r requirements.txt

  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout to correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: "3.10"
            cache: 'pip'
      - name: isort check
        working-directory: ./server  
        run: isort --check-only .
      - name: flake8 check
        working-directory: ./server  
        run: flake8 .
      - name: black check
        working-directory: ./server  
        run: black --check .
      - name: mypy check
        working-directory: ./server
        run: mypy .
  
