name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to correct branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies for CI environment
        run: npm ci
      - name: Check if code is pretty
        run: npm run prettier-check
      - name: Check if code is linted
        run: npm run lint
